#!/bin/bash

docker run --rm --detach --privileged -it \
	--net=host \
	-v $(pwd):/mnt \
	-v $HOME/learning:/root/learning \
        -v $HOME/code:/root/code \
	-v $HOME/ctf:/root/ctf \
	--hostname pwn \
	--name pwndock \
	pwndock \
	bash \
    && echo "[+] Started"
